# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginWithGoogle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginWithGoogle

	pod 'GoogleSignIn'

  target 'LoginWithGoogleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginWithGoogleUITests' do
    # Pods for testing
  end

end
